# Geo3K Multi-Turn Training Configuration
# Multi-turn agent with answer verification using agent_loop algorithm
# Use with: python opentinker/client/geo3k_tool_rl.py

# Project settings
project_name: opentinker
experiment_name: geo3k_multiturn

# Logging
logger_backends: ["console", "wandb"]

# Tracing (optional)
enable_tracing: true
weave_project: null

# WandB (optional)
wandb_key: 2ed6f8544ac3e30d5c08879166cc10d9c6232448

# Model and processor paths (VL model)
tokenizer_path: Qwen/Qwen2.5-VL-7B-Instruct
processor_path: Qwen/Qwen2.5-VL-7B-Instruct

# Data paths - use preprocessed Geo3K multi-turn data
data_path: ./data/geo3k_multiturn/train.parquet
val_data_path: ./data/geo3k_multiturn/test.parquet

# Training parameters
batch_size: 4 # Reduced from 16 for VL model
num_workers: 0
num_epochs: 5 # Total epochs
num_steps: null # Or set num_steps for step-based training
save_freq: -1 # Save checkpoint every N steps
test_freq: 5 # Validate every N steps

# Validation parameters
val_batch_size: 8 # Reduced from 32 for VL model

# Generation parameters
temperature: 1.0
top_p: 1.0
max_new_tokens: 4096 # Reduced from 4096
max_prompt_tokens: 4096 # Max prompt length including image tokens (VL: ~1000-5000 tokens per image)

# Algorithm - agent_loop for multi-turn with GymEnvironmentInteraction
algorithm: "agent_loop"

# RL Algorithm settings (passed to server via scheduler)
adv_estimator: "grpo"
rollout_n: 16 # Reduced from 5 for VL model

# Multi-turn configuration
multi_turn:
  max_user_turns: 3 # Max environment responses (verification feedback)
  max_assistant_turns: 4 # Max LLM responses (initial + refinements)
  max_tokens_per_turn: 1024 # Per-turn response limit
  weave_project: null
  experiment_name: "geo3k_multiturn"

# Interaction configuration - uses GymEnvironmentInteraction
interaction:
  name: geo3k_tool
  class_path: opentinker.environment.gym_environment_interaction.GymEnvironmentInteraction
  config:
    env_host: 0.0.0.0
    env_port: 8088
    env_endpoint: http://${interaction.config.env_host}:${interaction.config.env_port}
    max_steps: 3 # Max verification steps

# Scheduler settings
scheduler_url: "http://0.0.0.0:8780"
scheduler_api_key: null

# GPU settings
num_gpus: 4 # Adjust based on your setup
