# Gomoku Training Configuration
# Use with: python gomoku_client.py

# Project settings
project_name: opentinker
experiment_name: gomoku_training

# Logging
logger_backends: ["console","wandb"]

# Tracing (optional)
enable_tracing: true
weave_project: null

# WandB (optional)
wandb_key: null


# Model and tokenizer
tokenizer_path: null


# Training parameters
batch_size: 4
num_workers: 4
# Training duration - set ONE of these (num_steps takes precedence if both set)
num_epochs: null  # Number of epochs (null = use num_steps)
num_steps: 1000   # Total training steps (null = use num_epochs)
save_freq: 20000
test_freq: 10     # Validation frequency (every N steps)

# Validation parameters
val_batch_size: 50    # Total validation samples (null = 50)

# Model parameters
# Generation parameters
temperature: 1  # Lower temperature for more focused responses
top_p: 1
max_new_tokens: 8192  # TOTAL response budget for entire multi-turn trajectory (NOT per-turn!)
max_prompt_tokens: 4096

# Algorithm (must be agent_loop for multi-turn)
algorithm: "agent_loop"

# RL Algorithm settings (passed to server via scheduler)
# adv_estimator: "grpo" or "gae" (for PPO)
adv_estimator: "grpo"
# rollout_n: number of samples per prompt for GRPO (only used when adv_estimator=grpo)
rollout_n: 16

# Interaction configuration
interaction:
  name: gomoku
  class_path: opentinker.environment.gym_environment_interaction.GymEnvironmentInteraction
  config:
    env_endpoint: ${env_url}  # References top-level env_url
    max_steps: 81 # 这是后端GymEnvironmentInteraction的参数
    max_total_steps: 39  # 调用环境的step方法的最大次数限制（防止invalid move hacking）
    max_initial_moves: 0
    board_size: 9
    observation_template: "{observation}"
    empty_board_prob: 1.0


multi_turn:
    max_user_turns: ${interaction.config.max_total_steps} # 这是vllm的参数
    max_assistant_turns: ${interaction.config.max_total_steps} # 这是vllm的参数
    max_tokens_per_turn: 256  # Per-turn response limit (optional, null for no limit)
    # Weave tracing (optional - runs on SERVER side)
    weave_project: "zsqzz/gomoku-env-test"  # W&B project for tracing {'message': 'Entity opentinker not found', 'path': ['upsertModel']}
    experiment_name: "gomoku_interaction"  # Experiment name in Weave


# Server settings
scheduler_url: "http://0.0.0.0:8780"
scheduler_api_key: otk_98b8db24ccd64c92e1fdd9a232e209fa # this is user id
env_url: "http://0.0.0.0:8088"  # Game environment server URL

# GPU settings
num_gpus: 2

